version: '3.8'

services:
  app:
    container_name: ng-frontend-dev
    image: node:alpine
    command: sh -c "npm i && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
